### PR TITLE
Fix pin not showing on map for joplin pole and substation damage

### LINKED ISSUE #436: Joplin Pole and Substation missing map pin
Only for joplin seems like it's missing the map pin for pole/substation damage as well as their comparison

Image

### PR DESCRIPTION
**Pull request by Rashmil-1999**

### CODE REVIEW

File: src/components/childComponents/map/Map.jsx [hunk 1]
```diff
@@ -253,7 +253,10 @@ const Map = (props) => {
 						.then((json) => {
 							let bldg = json.features;
 							if (bldg.length > 0) {
-								const returnCoordinates = bldg[0]?.geometry?.coordinates;
+								let returnCoordinates = bldg[0]?.geometry?.coordinates;
+								if (returnCoordinates.length === 1) {
+									returnCoordinates = returnCoordinates[0];
+								}
```
Comment (longshuicy) [inline src/components/childComponents/map/Map.jsx:259]: Oh what happened here?

Comment (Rashmil-1999) [reply src/components/childComponents/map/Map.jsx:259]: The returned response has the coordinates wrapped in an array. So we were passing `[Array(2)]` -> `[[lat, long]]` so I checked if that's the case, then I extracted the inner array. This only happens for pole damage and substation damage.

**Review by Vismayak — APPROVED** [review]
