### PR TITLE
fixed the bar when the small screen

### LINKED ISSUE #139: fix status bar appearance for a smaller screen/ different browser
Try Safari, it looks like:
image

But it should looks like this:
image

### PR DESCRIPTION
**Pull request by ywkim312**
@longshuicy I tested all the parameters in material UI's flex and nothing worked but the one in the PR. It is neither the material UI parameter nor dynamic. It gives the fixed pixel size for the given box div tag. If this div size is not enough, flex box will sub divide the rows to or even three no matter what. Also, please test it in safari please.

### CODE REVIEW

File: src/components/childComponents/step/StepStatus.jsx [hunk 1]
```diff
@@ -38,7 +38,7 @@ const StepStatus = ({ step, substep }) => {
 
 	return (
 		<Box>
-			<div className={"statusBox"}>
+			<div className={"statusBox"} style={{ width: 380 }}>
```
Comment (longshuicy) [inline src/components/childComponents/step/StepStatus.jsx]: Can you actually update this width in the `.statusBox css` under `src/styles/step-status.css`

Comment (ywkim312) [reply src/components/childComponents/step/StepStatus.jsx]: updated

**Review by longshuicy — APPROVED** [review]
